---
# tasks file for vnc-server
- name: installing tigervnc
  apt:
    name: tigervnc-standalone-server
    state: present

- name: Crate .vnc directoy for lfnwvideo user
  file:
    path: "/home/lfnwvideo/.vnc/"
    owner: "lfnwvideo"
    group: "lfnwvideo"
    state: directory

# NB: we are not using the passwd file, but tigervnc complains if is missing
- name: Copy vnc config files to .vnc
  copy:
    src: "{{ role_path }}/files/dot-vnc/{{ item }}"
    dest: "/home/lfnwvideo/.vnc/"
    owner: "lfnwvideo"
    group: "lfnwvideo"
    mode: 0600
  with_items:
     - passwd
     - vnc.conf

- name: Copy X startup file to .vnc
  copy:
    src: "{{ role_path }}/files/dot-vnc/{{ item }}"
    dest: "/home/lfnwvideo/.vnc/"
    owner: "lfnwvideo"
    group: "lfnwvideo"
    mode: 0755
  with_items:
     - xstartup

- name: Copy vnc startup script
  copy:
    src: "{{ role_path }}/files/bin/run-vncserver.sh"
    dest: "/home/lfnwvideo/bin/"
    owner: "lfnwvideo"
    group: "lfnwvideo"
    mode: 0700

- name: Setup crontab to run vnc server at boot
  cron:
    name: "vnc-server"
    special_time: reboot
    user: lfnwvideo
    job: "sleep 10;/home/lfnwvideo/bin/run-vncserver.sh"

- name: Allow VNC connections in firewall
  ufw:
    rule: allow
    port: 5901
    proto: tcp
    comment: "VNC remote desktop"

- name: Add lfnwvideo to required groups
  user:
    name: "lfnwvideo"
    groups: "audio,video,bluetooth"
    append: yes

- name: Copy xfce terminal config
  copy:
    src: "{{ role_path }}/files/terminalrc"
    dest: "/home/lfnwvideo/.config/xfce4/terminal/terminalrc"
    owner: "lfnwvideo"
    group: "lfnwvideo"
    mode: 0664
    force: no

- name: Copy virtgl deb to Downloads
  copy:
    src: "{{ item }}"
    dest: /home/lfnwvideo/Downloads/
    owner: "lfnwvideo"
    group: "lfnwvideo"
    mode: 0664
    force: no
  with_fileglob:
    - "{{ role_path }}/files/virtgl/*"

- name: Install virtgl package
  apt:
    deb:  /home/lfnwvideo/Downloads/virtualgl_2.6.1_amd64.deb
    state: present
