---
# tasks file for controller

- name: Create LFNW directory
  file:
    path: /home/lfnwvideo/LFNW/raw_videos
    state: directory
    owner: lfnwvideo
    group: lfnwvideo
    mode: 0755
    recurse: yes
