---
# tasks file for obs

- name: installing ffmpeg
  apt:
    name: ffmpeg
    state: latest

- name: Add obs repo to system
  apt_repository:
    repo: ppa:obsproject/obs-studio

- name: installing Obs Studio
  apt:
    name: obs-studio
    state: latest
    update_cache: yes

- name: Copy image sources to Pictures folder
  copy:
    src: "{{ item }}"
    dest: "/home/lfnwvideo/Pictures"
    owner: "lfnwvideo"
    group: "lfnwvideo"
    mode: 0644
  with_fileglob:
    - "{{ role_path }}/files/Pictures/*"

- name: Create local config directories if they don't exist
  file:
    path: "/home/lfnwvideo/{{ item }}"
    state: directory
    owner: lfnwvideo
    group: lfnwvideo
    mode: 0775
  with_items:
     - .local/share/applications
     - .gnome/apps

- name: Copy obs desktop files that use virtgl
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/home/lfnwvideo/{{ item }}"
    owner: "lfnwvideo"
    group: "lfnwvideo"
    mode: 0664
  with_items:
     - .local/share/applications/obs.desktop
     - .gnome/apps/obs.desktop

- name: Copy profiles and scene collections
  synchronize:
    src: "{{ role_path }}/files/.config/obs-studio"
    dest: /home/lfnwvideo/.config
    archive: no
    perms: yes
    recursive: yes
    delete: yes
    rsync_path: "/usr/bin/rsync"
