---
# tasks file for common
- name: installing fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: installing mediainfo
  apt:
    name: mediainfo
    state: present

- name: installing ufw
  apt:
    name: ufw
    state: present

- name: Enable UFW
  ufw:
    state: enabled
    logging: on

- name: Allow ssh connections
  ufw:
    rule: allow
    name: OpenSSH

- name: Install sftp utils
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - sshfs
    - filezilla

- name: Copy xfce terminal config
  copy:
    src: "{{ role_path }}/files/terminalrc"
    dest: "/home/lfnwvideo/.config/xfce4/terminal/terminalrc"
    owner: "lfnwvideo"
    group: "lfnwvideo"
    mode: 0664
    force: no

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
    backup: no
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
