---
# tasks file for common
- name: installing fail2ban
  apt:
    name: fail2ban
    state: present

- name: installing mediainfo
  apt:
    name: mediainfo
    state: present

- name: installing ufw
  apt:
    name: ufw
    state: present

- name: Enable UFW
  ufw:
    state: enabled
    logging: on

- name: Allow ssh connections
  ufw:
    rule: allow
    name: OpenSSH
